vim.g.mapleader = " "

vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")

-- Держит курсор на виду
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")

-- greatest remap ever
vim.keymap.set("x", "<leader>p", [["_dP]])

-- next greatest remap ever : asbjornHaland
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])

-- deleting to void register
vim.keymap.set({ "n", "v" }, "<leader>d", "\"_d")

vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set({"n", "v"}, "<leader>f", vim.lsp.buf.format)
vim.keymap.set("n", "[q", "<cmd>cnext<CR>zz")
vim.keymap.set("n", "]q", "<cmd>cprev<CR>zz")
vim.keymap.set("n", "<leader>k", "<cmd>lnext<CR>zz")
vim.keymap.set("n", "<leader>j", "<cmd>lprev<CR>zz")

vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<C-b>", "<C-v>")

vim.keymap.set({ "n", "v" }, "ц", "e")
vim.keymap.set({ "n", "v" }, "у", "e")
vim.keymap.set({ "n", "v" }, "к", "r")
vim.keymap.set({ "n", "v" }, "е", "t")
vim.keymap.set({ "n", "v" }, "н", "y")
vim.keymap.set({ "n", "v" }, "г", "u")
vim.keymap.set({ "n", "v" }, "ш", "i")
vim.keymap.set({ "n", "v" }, "щ", "o")
vim.keymap.set({ "n", "v" }, "з", "p")
vim.keymap.set({ "n", "v" }, "х", "[")
vim.keymap.set({ "n", "v" }, "ъ", "]")
vim.keymap.set({ "n", "v" }, "ф", "a")
vim.keymap.set({ "n", "v" }, "ы", "s")
vim.keymap.set({ "n", "v" }, "в", "d")
vim.keymap.set({ "n", "v" }, "а", "f")
vim.keymap.set({ "n", "v" }, "п", "g")
vim.keymap.set({ "n", "v" }, "р", "h")
vim.keymap.set({ "n", "v" }, "о", "j")
vim.keymap.set({ "n", "v" }, "л", "k")
vim.keymap.set({ "n", "v" }, "д", "l")
vim.keymap.set({ "n", "v" }, "ж", ";")
vim.keymap.set({ "n", "v" }, "э", "'")
vim.keymap.set({ "n", "v" }, "ё", "\\")
vim.keymap.set({ "n", "v" }, "я", "z")
vim.keymap.set({ "n", "v" }, "ч", "x")
vim.keymap.set({ "n", "v" }, "с", "c")
vim.keymap.set({ "n", "v" }, "м", "v")
vim.keymap.set({ "n", "v" }, "и", "b")
vim.keymap.set({ "n", "v" }, "т", "n")
vim.keymap.set({ "n", "v" }, "ь", "m")
vim.keymap.set({ "n", "v" }, "б", ",")
vim.keymap.set({ "n", "v" }, "ю", ".")
vim.keymap.set({ "n", "v" }, "Й", "Q")
vim.keymap.set({ "n", "v" }, "Ц", "W")
vim.keymap.set({ "n", "v" }, "У", "E")
vim.keymap.set({ "n", "v" }, "К", "R")
vim.keymap.set({ "n", "v" }, "Е", "T")
vim.keymap.set({ "n", "v" }, "Н", "Y")
vim.keymap.set({ "n", "v" }, "Г", "U")
vim.keymap.set({ "n", "v" }, "Ш", "I")
vim.keymap.set({ "n", "v" }, "Щ", "O")
vim.keymap.set({ "n", "v" }, "З", "P")
vim.keymap.set({ "n", "v" }, "Х", "{")
vim.keymap.set({ "n", "v" }, "Ъ", "}")
vim.keymap.set({ "n", "v" }, "Ф", "A")
vim.keymap.set({ "n", "v" }, "Ы", "S")
vim.keymap.set({ "n", "v" }, "В", "D")
vim.keymap.set({ "n", "v" }, "А", "F")
vim.keymap.set({ "n", "v" }, "П", "G")
vim.keymap.set({ "n", "v" }, "Р", "H")
vim.keymap.set({ "n", "v" }, "О", "J")
vim.keymap.set({ "n", "v" }, "Л", "K")
vim.keymap.set({ "n", "v" }, "Д", "L")
vim.keymap.set({ "n", "v" }, "Ж", ":")
vim.keymap.set({ "n", "v" }, "Э", "\"")
vim.keymap.set({ "n", "v" }, "Я", "Z")
vim.keymap.set({ "n", "v" }, "Ч", "X")
vim.keymap.set({ "n", "v" }, "С", "C")
vim.keymap.set({ "n", "v" }, "М", "V")
vim.keymap.set({ "n", "v" }, "И", "B")
vim.keymap.set({ "n", "v" }, "Т", "N")
vim.keymap.set({ "n", "v" }, "Ь", "M")
vim.keymap.set({ "n", "v" }, "Б", "<")
vim.keymap.set({ "n", "v" }, "Ю", ">")
vim.keymap.set({ "n", "v" }, "Ё", "/")
